### ISSUE TITLE
IOError: [Errno 13] Permission denied: '/usr/lib/systemd/system/auditd.service'

### ISSUE THREAD

**Issue by bcoles** [initstring/uptux#4]
`/usr/lib/systemd/system/auditd.service` is not readable by default, causing further checks to fail.

Tested on a mostly clean CentOS 7.1.1503 box.

```
$ ls -la /usr/lib/systemd/system/auditd.service
-rw-r-----. 1 root root 669 Mar  6  2015 /usr/lib/systemd/system/auditd.service

$ cat /etctos-release
CentOS Linux release 7.1.1503 (Core) 

$ uname -a
Linux localhost.localdomain 3.10.0-229.el7.x86_64 #1 SMP Fri Mar 6 11:36:42 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

```
$ ./uptux.py 




                      ____ ___      ___________            
                     |    |   \_____\__    ___/_ _____  ___
                     |    |   /\____ \|    | |  |  \  \/  /
                     |    |  / |  |_> >    | |  |  />    < 
                     |______/  |   __/|____| |____//__/\_ \
                               |__|                      \/
                     
                     
                   
                        PrivEsc for modern Linux systems
                          github.com/initstring/uptux





++++++++++  uptux_check_sysinfo: Gather basic OS information  ++++++++++


[*] Starting module at 2018-04-23-07.04.12


Host: localhost.localdomain
OS: Linux, #1 SMP Fri Mar 6 11:36:42 UTC 2015
Kernel: 3.10.0-229.el7.x86_64
Current user: user (UID 1000 GID 1000)
Member of following groups:
  user


[*] Finished module at 2018-04-23-07.04.12



++++++++++  uptux_check_systemd_paths: Check if systemd PATH is writeable  ++++++++++


[*] Starting module at 2018-04-23-07.04.12


[+] No systemd paths are writeable. This is expected...


[*] Finished module at 2018-04-23-07.04.12



++++++++++  uptux_check_services: Inspect systemd service unit files  ++++++++++


[*] Starting module at 2018-04-23-07.04.12


[*] Found 356 service units to analyse...


[*] Checking permissions on service unit files...

[+] No writeable targets. This is expected...

[*] Checking for relative paths in service unit files [check 1]...
Traceback (most recent call last):
  File "./uptux.py", line 746, in <module>
    main()
  File "./uptux.py", line 739, in main
    check_handler(check, check_name, check_desc)
  File "./uptux.py", line 120, in check_handler
    check()
  File "./uptux.py", line 529, in uptux_check_services
    message_box=box)
  File "./uptux.py", line 238, in regex_vuln_search
    file_object = open(file_name, 'r')
IOError: [Errno 13] Permission denied: '/usr/lib/systemd/system/auditd.service'

```

Comparatively, most other services are readable:

```
$ ls -la /usr/lib/systemd/system/
total 1008
drwxr-xr-x. 26 root root 12288 Apr 23 06:01 .
drwxr-xr-x. 12 root root  4096 Mar 31  2015 ..
-rw-r--r--.  1 root root   421 Jun 10  2014 accounts-daemon.service
-rw-r--r--.  1 root root   645 Mar 26  2015 anaconda-direct.service
-rw-r--r--.  1 root root   185 Mar 26  2015 anaconda-nm-config.service
-rw-r--r--.  1 root root   660 Mar 26  2015 anaconda-noshell.service
-rw-r--r--.  1 root root   387 Mar 26  2015 anaconda.service
-rw-r--r--.  1 root root   684 Mar 26  2015 anaconda-shell@.service
-rw-r--r--.  1 root root   322 Mar 26  2015 anaconda-sshd.service
-rw-r--r--.  1 root root   312 Mar 26  2015 anaconda.target
drwxr-xr-x.  2 root root  4096 Apr 23 06:01 anaconda.target.wants
-rw-r--r--.  1 root root   498 Mar 26  2015 anaconda-tmux@.service
-rw-r--r--.  1 root root   275 Jun 10  2014 arp-ethers.service
-rw-r--r--.  1 root root   205 Oct  7  2014 atd.service
-rw-r-----.  1 root root   669 Mar  6  2015 auditd.service
lrwxrwxrwx.  1 root root    14 Mar 31  2015 autovt@.service -> getty@.service
-rw-r--r--.  1 root root  1044 Mar  6  2015 avahi-daemon.service
-rw-r--r--.  1 root root   874 Mar  6  2015 avahi-daemon.socket
-rw-r--r--.  1 root root   546 Mar  6  2015 basic.target
drwxr-xr-x.  2 root root  4096 Mar 31  2015 basic.target.wants
-r--r--r--.  1 root root   341 Mar  6  2015 blk-availability.service
-rw-r--r--.  1 root root   176 Jun 10  2014 bluetooth.service
-rw-r--r--.  1 root root   379 Mar  6  2015 bluetooth.target
-rw-r--r--.  1 root root   160 Jan 15  2015 brandbot.path
-rw-r--r--.  1 root root   101 Jan 15  2015 brandbot.service
-rw-r--r--.  1 root root   491 Jun 10  2014 canberra-system-bootup.service
-rw-r--r--.  1 root root   509 Jun 10  2014 canberra-system-shutdown-reboot.service
-rw-r--r--.  1 root root   466 Jun 10  2014 canberra-system-shutdown.service
-rw-r--r--.  1 root root   319 Jun 19  2014 chronyd.service
-rw-r--r--.  1 root root   419 Jun 19  2014 chrony-wait.service
-rw-r--r--.  1 root root   295 Jun 10  2014 colord.service
-rw-r--r--.  1 root root   737 Mar  6  2015 console-getty.service
-rw-r--r--.  1 root root   745 Mar  6  2015 console-shell.service
-rw-r--r--.  1 root root   294 Mar  6  2015 cpupower.service
-rw-r--r--.  1 root root   284 Jul 31  2014 crond.service
-rw-r--r--.  1 root root   366 Mar  6  2015 cryptsetup.target
lrwxrwxrwx.  1 root root    13 Mar 31  2015 ctrl-alt-del.target -> reboot.target
lrwxrwxrwx.  1 root root    25 Mar 31  2015 dbus-org.freedesktop.hostname1.service -> systemd-hostnamed.service
lrwxrwxrwx.  1 root root    23 Mar 31  2015 dbus-org.freedesktop.locale1.service -> systemd-localed.service
lrwxrwxrwx.  1 root root    22 Mar 31  2015 dbus-org.freedesktop.login1.service -> systemd-logind.service
lrwxrwxrwx.  1 root root    24 Mar 31  2015 dbus-org.freedesktop.machine1.service -> systemd-machined.service
lrwxrwxrwx.  1 root root    25 Mar 31  2015 dbus-org.freedesktop.timedate1.service -> systemd-timedated.service
-rw-r--r--.  1 root root   345 Mar  6  2015 dbus.service
-rw-r--r--.  1 root root   106 Mar  6  2015 dbus.socket
drwxr-xr-x.  2 root root    24 Mar 31  2015 dbus.target.wants
-rw-r--r--.  1 root root   984 Mar  6  2015 debug-shell.service
lrwxrwxrwx.  1 root root    16 Mar 31  2015 default.target -> graphical.target
drwxr-xr-x.  2 root root     6 Mar  6  2015 default.target.wants
-rw-r--r--.  1 root root   636 Mar  6  2015 dev-hugepages.mount
-rw-r--r--.  1 root root   590 Mar  6  2015 dev-mqueue.mount
-r--r--r--.  1 root root   334 Mar  6  2015 dm-event.service
-r--r--r--.  1 root root   248 Mar  6  2015 dm-event.socket
-r--r--r--.  1 root root   357 Mar  6  2015 dmraid-activation.service
-rw-r--r--.  1 root root   140 Jun 10  2014 dnsmasq.service
lrwxrwxrwx.  1 root root    55 Mar 31  2015 dracut-cmdline.service -> ../../dracut/modules.d/98systemd/dracut-cmdline.service
lrwxrwxrwx.  1 root root    57 Mar 31  2015 dracut-initqueue.service -> ../../dracut/modules.d/98systemd/dracut-initqueue.service
lrwxrwxrwx.  1 root root    53 Mar 31  2015 dracut-mount.service -> ../../dracut/modules.d/98systemd/dracut-mount.service
lrwxrwxrwx.  1 root root    57 Mar 31  2015 dracut-pre-mount.service -> ../../dracut/modules.d/98systemd/dracut-pre-mount.service
lrwxrwxrwx.  1 root root    57 Mar 31  2015 dracut-pre-pivot.service -> ../../dracut/modules.d/98systemd/dracut-pre-pivot.service
lrwxrwxrwx.  1 root root    59 Mar 31  2015 dracut-pre-trigger.service -> ../../dracut/modules.d/98systemd/dracut-pre-trigger.service
lrwxrwxrwx.  1 root root    56 Mar 31  2015 dracut-pre-udev.service -> ../../dracut/modules.d/98systemd/dracut-pre-udev.service
lrwxrwxrwx.  1 root root    56 Mar 31  2015 dracut-shutdown.service -> ../../dracut/modules.d/98systemd/dracut-shutdown.service
-rwxr-xr-x.  1 root root   208 Mar  4  2014 ebtables.service
-rw-r--r--.  1 root root   941 Mar  6  2015 emergency.service
-rw-r--r--.  1 root root   431 Mar  6  2015 emergency.target
-rw-r--r--.  1 root root   282 Mar 10  2015 fcoe.service
-rw-r--r--.  1 root root   440 Mar  6  2015 final.target
-rw-r--r--.  1 root root   577 Mar  6  2015 firewalld.service
-rw-r--r--.  1 root root   469 Mar  4  2014 firstboot-graphical.service
-rw-r--r--.  1 root root   165 Jun 24  2014 fprintd.service
-rw-r--r--.  1 root root   502 Mar  6  2015 gdm.service
-rw-r--r--.  1 root root  1515 Mar  6  2015 getty@.service
-rw-r--r--.  1 root root   460 Mar  6  2015 getty.target
-rw-r--r--.  1 root root   522 Mar  6  2015 graphical.target
drwxr-xr-x.  2 root root     6 Mar  6  2015 graphical.target.wants
-rw-r--r--.  1 root root   565 Mar  6  2015 halt-local.service
-rw-r--r--.  1 root root   487 Mar  6  2015 halt.target
drwxr-xr-x.  2 root root    34 Mar 31  2015 halt.target.wants
-rw-r--r--.  1 root root   447 Mar  6  2015 hibernate.target
-rw-r--r--.  1 root root   468 Mar  6  2015 hybrid-sleep.target
-rw-r--r--.  1 root root   840 Mar 13  2014 initial-setup-text.service
-rw-r--r--.  1 root root   596 Mar  6  2015 initrd-cleanup.service
-rw-r--r--.  1 root root   536 Mar  6  2015 initrd-fs.target
-rw-r--r--.  1 root root   763 Mar  6  2015 initrd-parse-etc.service
-rw-r--r--.  1 root root   509 Mar  6  2015 initrd-root-fs.target
-rw-r--r--.  1 root root   606 Mar  6  2015 initrd-switch-root.service
-rw-r--r--.  1 root root   691 Mar  6  2015 initrd-switch-root.target
drwxr-xr-x.  2 root root    70 Mar 31  2015 initrd-switch-root.target.wants
-rw-r--r--.  1 root root   654 Mar  6  2015 initrd.target
drwxr-xr-x.  2 root root  4096 Mar 31  2015 initrd.target.wants
-rw-r--r--.  1 root root   668 Mar  6  2015 initrd-udevadm-cleanup-db.service
-rw-r--r--.  1 root root   163 Mar 26  2015 instperf.service
-rw-r--r--.  1 root root   180 Mar  6  2015 iprdump.service
-rw-r--r--.  1 root root   139 Mar  6  2015 iprinit.service
-rw-r--r--.  1 root root   143 Mar  6  2015 iprupdate.service
-rw-r--r--.  1 root root   173 Mar  6  2015 iprutils.target
-rw-r--r--.  1 root root   948 Mar  6  2015 ipsec.service
-rw-r--r--.  1 root root   209 Mar  6  2015 irqbalance.service
-rw-r--r--.  1 root root   337 Mar  6  2015 iscsid.service
-rw-r--r--.  1 root root   175 Mar  6  2015 iscsid.socket
-rw-r--r--.  1 root root   645 Mar  6  2015 iscsi.service
-rw-r--r--.  1 root root   425 Mar  6  2015 iscsi-shutdown.service
-rw-r--r--.  1 root root   356 Mar  6  2015 iscsiuio.service
-rw-r--r--.  1 root root   165 Mar  6  2015 iscsiuio.socket
-rw-r--r--.  1 root root   277 Mar 10  2015 kdump.service
-rw-r--r--.  1 root root   501 Mar  6  2015 kexec.target
drwxr-xr-x.  2 root root    35 Mar 31  2015 kexec.target.wants
-rw-r--r--.  1 root root   721 Mar  6  2015 kmod-static-nodes.service
-rw-r--r--.  1 root root   228 Mar  6  2015 libstoragemgmt.service
-rw-r--r--.  1 root root   243 Mar  6  2015 lldpad.service
-rw-r--r--.  1 root root    99 Mar  6  2015 lldpad.socket
-rw-r--r--.  1 root root   395 Mar  6  2015 local-fs-pre.target
-rw-r--r--.  1 root root   489 Mar  6  2015 local-fs.target
drwxr-xr-x.  2 root root    99 Mar 31  2015 local-fs.target.wants
-r--r--r--.  1 root root   349 Mar  6  2015 lvm2-lvmetad.service
-r--r--r--.  1 root root   215 Mar  6  2015 lvm2-lvmetad.socket
-r--r--r--.  1 root root   645 Mar  6  2015 lvm2-monitor.service
-r--r--r--.  1 root root   369 Mar  6  2015 lvm2-pvscan@.service
-rw-r--r--.  1 root root   405 Mar  6  2015 machine.slice
-rw-r--r--.  1 root root   485 Mar  6  2015 mdadm-grow-continue@.service
-rw-r--r--.  1 root root   145 Mar  6  2015 mdadm-last-resort@.service
-rw-r--r--.  1 root root   176 Mar  6  2015 mdadm-last-resort@.timer
-rw-r--r--.  1 root root   330 Mar  6  2015 mdmonitor.service
-rw-r--r--.  1 root root  1038 Mar  6  2015 mdmon@.service
lrwxrwxrwx.  1 root root    12 Mar 31  2015 messagebus.service -> dbus.service
-rw-r--r--.  1 root root   249 Mar  6  2015 microcode.service
-rw-r--r--.  1 root root   567 Mar  6  2015 multipathd.service
-rw-r--r--.  1 root root   524 Mar  6  2015 multi-user.target
drwxr-xr-x.  2 root root  4096 Mar 31  2015 multi-user.target.wants
-rw-r--r--.  1 root root   353 Mar  6  2015 NetworkManager-dispatcher.service
-rw-r--r--.  1 root root   419 Mar  6  2015 NetworkManager.service
-rw-r--r--.  1 root root   284 Mar  6  2015 NetworkManager-wait-online.service
-rw-r--r--.  1 root root   464 Mar  6  2015 network-online.target
drwxr-xr-x.  2 root root    47 Mar 31  2015 network-online.target.wants
-rw-r--r--.  1 root root   433 Mar  6  2015 network.target
-rw-r--r--.  1 root root   514 Mar  6  2015 nss-lookup.target
-rw-r--r--.  1 root root   473 Mar  6  2015 nss-user-lookup.target
-rw-r--r--.  1 root root   257 Dec 20  2014 ntpdate.service
-rw-r--r--.  1 root root   271 Mar  6  2015 oddjobd.service
-rw-r--r--.  1 root root   180 Jun 20  2014 packagekit-offline-update.service
-rw-r--r--.  1 root root   354 Mar  6  2015 paths.target
-rw-r--r--.  1 root root   381 Mar 10  2015 plymouth-halt.service
-rw-r--r--.  1 root root   396 Mar 10  2015 plymouth-kexec.service
-rw-r--r--.  1 root root   393 Mar 10  2015 plymouth-poweroff.service
-rw-r--r--.  1 root root   235 Mar 10  2015 plymouth-quit.service
-rw-r--r--.  1 root root   243 Mar 10  2015 plymouth-quit-wait.service
-rw-r--r--.  1 root root   282 Mar 10  2015 plymouth-read-write.service
-rw-r--r--.  1 root root   386 Mar 10  2015 plymouth-reboot.service
-rw-r--r--.  1 root root   546 Mar 10  2015 plymouth-start.service
-rw-r--r--.  1 root root   295 Mar 10  2015 plymouth-switch-root.service
-rw-r--r--.  1 root root   172 Jun 10  2014 polkit.service
-rw-r--r--.  1 root root   500 Mar  6  2015 poweroff.target
drwxr-xr-x.  2 root root    38 Mar 31  2015 poweroff.target.wants
-rw-r--r--.  1 root root   377 Mar  6  2015 printer.target
-rw-r--r--.  1 root root   693 Mar  6  2015 proc-sys-fs-binfmt_misc.automount
-rw-r--r--.  1 root root   603 Mar  6  2015 proc-sys-fs-binfmt_misc.mount
-rw-r--r--.  1 root root   303 Mar  6  2015 psacct.service
-rw-r--r--.  1 root root   643 Mar  6  2015 quotaon.service
-rw-r--r--.  1 root root   653 Mar  6  2015 rc-local.service
-rw-r--r--.  1 root root   243 Jun 10  2014 rdisc.service
-rw-r--r--.  1 root root   165 Jun 11  2014 realmd.service
-rw-r--r--.  1 root root   493 Mar  6  2015 reboot.target
drwxr-xr-x.  2 root root    36 Mar 31  2015 reboot.target.wants
-rw-r--r--.  1 root root   396 Mar  6  2015 remote-fs-pre.target
-rw-r--r--.  1 root root   482 Mar  6  2015 remote-fs.target
-rw-r--r--.  1 root root   958 Mar  6  2015 rescue.service
-rw-r--r--.  1 root root   486 Mar  6  2015 rescue.target
-rw-r--r--.  1 root root   371 Jan 15  2015 rhel-autorelabel-mark.service
-rw-r--r--.  1 root root   407 Jan 15  2015 rhel-autorelabel.service
-rw-r--r--.  1 root root   366 Jan 15  2015 rhel-configure.service
-rw-r--r--.  1 root root   182 Jan 15  2015 rhel-dmesg.service
-rw-r--r--.  1 root root   312 Jan 15  2015 rhel-domainname.service
-rw-r--r--.  1 root root   409 Jan 15  2015 rhel-import-state.service
-rw-r--r--.  1 root root   398 Jan 15  2015 rhel-loadmodules.service
-rw-r--r--.  1 root root   366 Jan 15  2015 rhel-readonly.service
-rw-r--r--.  1 root root   129 Mar  6  2015 rngd.service
-rw-r--r--.  1 root root   500 Mar  6  2015 rpcbind.target
-rw-r--r--.  1 root root   237 Jun 10  2014 rsyncd.service
-rw-r--r--.  1 root root   138 Jun 10  2014 rsyncd.socket
-rw-r--r--.  1 root root   258 Oct 14  2014 rsyslog.service
-rw-r--r--.  1 root root  1053 Mar  6  2015 rtkit-daemon.service
lrwxrwxrwx.  1 root root    15 Mar 31  2015 runlevel0.target -> poweroff.target
lrwxrwxrwx.  1 root root    13 Mar 31  2015 runlevel1.target -> rescue.target
drwxr-xr-x.  2 root root    49 Mar 31  2015 runlevel1.target.wants
lrwxrwxrwx.  1 root root    17 Mar 31  2015 runlevel2.target -> multi-user.target
drwxr-xr-x.  2 root root    49 Mar 31  2015 runlevel2.target.wants
lrwxrwxrwx.  1 root root    17 Mar 31  2015 runlevel3.target -> multi-user.target
drwxr-xr-x.  2 root root    49 Mar 31  2015 runlevel3.target.wants
lrwxrwxrwx.  1 root root    17 Mar 31  2015 runlevel4.target -> multi-user.target
drwxr-xr-x.  2 root root    49 Mar 31  2015 runlevel4.target.wants
lrwxrwxrwx.  1 root root    16 Mar 31  2015 runlevel5.target -> graphical.target
drwxr-xr-x.  2 root root    49 Mar 31  2015 runlevel5.target.wants
lrwxrwxrwx.  1 root root    13 Mar 31  2015 runlevel6.target -> reboot.target
-rw-r--r--.  1 root root  1051 Mar  6  2015 serial-getty@.service
-rw-r--r--.  1 root root   402 Mar  6  2015 shutdown.target
drwxr-xr-x.  2 root root    36 Mar 31  2015 shutdown.target.wants
-rw-r--r--.  1 root root   362 Mar  6  2015 sigpwr.target
-rw-r--r--.  1 root root   420 Mar  6  2015 sleep.target
-rw-r--r--.  1 root root   403 Mar  6  2015 -.slice
-rw-r--r--.  1 root root   409 Mar  6  2015 slices.target
-rw-r--r--.  1 root root   380 Mar  6  2015 smartcard.target
-rw-r--r--.  1 root root   290 Jun 10  2014 smartd.service
-rw-r--r--.  1 root root   356 Mar  6  2015 sockets.target
drwxr-xr-x.  2 root root  4096 Mar 31  2015 sockets.target.wants
-rw-r--r--.  1 root root   380 Mar  6  2015 sound.target
-rw-r--r--.  1 root root   431 Mar  6  2015 spice-vdagentd.service
-rw-r--r--.  1 root root    49 Mar  6  2015 spice-vdagentd.target
-rw-r--r--.  1 root root   307 Mar  6  2015 sshd-keygen.service
-rw-r--r--.  1 root root   316 Mar  6  2015 sshd.service
-rw-r--r--.  1 root root   215 Mar  6  2015 sshd@.service
-rw-r--r--.  1 root root   136 Mar  6  2015 sshd.socket
-rw-r--r--.  1 root root   441 Mar  6  2015 suspend.target
-rw-r--r--.  1 root root   353 Mar  6  2015 swap.target
-rw-r--r--.  1 root root   681 Mar  6  2015 sys-fs-fuse-connections.mount
-rw-r--r--.  1 root root   540 Mar  6  2015 sysinit.target
drwxr-xr-x.  2 root root  4096 Mar 31  2015 sysinit.target.wants
-rw-r--r--.  1 root root   685 Mar  6  2015 sys-kernel-config.mount
-rw-r--r--.  1 root root   628 Mar  6  2015 sys-kernel-debug.mount
-rw-r--r--.  1 root root  1235 Mar  6  2015 syslog.socket
drwxr-xr-x.  2 root root     6 Mar  6  2015 syslog.target.wants
-rw-r--r--.  1 root root   421 Mar  6  2015 sysstat.service
-rw-r--r--.  1 root root   646 Mar  6  2015 systemd-ask-password-console.path
-rw-r--r--.  1 root root   657 Mar  6  2015 systemd-ask-password-console.service
-rw-r--r--.  1 root root   419 Mar 10  2015 systemd-ask-password-plymouth.path
-rw-r--r--.  1 root root   400 Mar 10  2015 systemd-ask-password-plymouth.service
-rw-r--r--.  1 root root   574 Mar  6  2015 systemd-ask-password-wall.path
-rw-r--r--.  1 root root   689 Mar  6  2015 systemd-ask-password-wall.service
-rw-r--r--.  1 root root   784 Mar  6  2015 systemd-backlight@.service
-rw-r--r--.  1 root root  1015 Mar  6  2015 systemd-binfmt.service
-rw-r--r--.  1 root root   696 Mar  6  2015 systemd-fsck-root.service
-rw-r--r--.  1 root root   682 Mar  6  2015 systemd-fsck@.service
-rw-r--r--.  1 root root   548 Mar  6  2015 systemd-halt.service
-rw-r--r--.  1 root root   505 Mar  6  2015 systemd-hibernate.service
-rw-r--r--.  1 root root   642 Mar  6  2015 systemd-hostnamed.service
-rw-r--r--.  1 root root   523 Mar  6  2015 systemd-hybrid-sleep.service
-rw-r--r--.  1 root root   484 Mar  6  2015 systemd-initctl.service
-rw-r--r--.  1 root root   489 Mar  6  2015 systemd-initctl.socket
-rw-r--r--.  1 root root   940 Mar  6  2015 systemd-journald.service
-rw-r--r--.  1 root root   833 Mar  6  2015 systemd-journald.socket
-rw-r--r--.  1 root root   702 Mar  6  2015 systemd-journal-flush.service
-rw-r--r--.  1 root root   561 Mar  6  2015 systemd-kexec.service
-rw-r--r--.  1 root root   591 Mar  6  2015 systemd-localed.service
-rw-r--r--.  1 root root   972 Mar  6  2015 systemd-logind.service
-rw-r--r--.  1 root root   667 Mar  6  2015 systemd-machined.service
-rw-r--r--.  1 root root  1029 Mar  6  2015 systemd-modules-load.service
-rw-r--r--.  1 root root   495 Mar  6  2015 systemd-nspawn@.service
-rw-r--r--.  1 root root   557 Mar  6  2015 systemd-poweroff.service
-rw-r--r--.  1 root root   689 Mar  6  2015 systemd-quotacheck.service
-rw-r--r--.  1 root root   777 Mar  6  2015 systemd-random-seed.service
-rw-r--r--.  1 root root   845 Mar  6  2015 systemd-readahead-collect.service
-rw-r--r--.  1 root root   642 Mar  6  2015 systemd-readahead-done.service
-rw-r--r--.  1 root root   620 Mar  6  2015 systemd-readahead-done.timer
-rw-r--r--.  1 root root   555 Mar  6  2015 systemd-readahead-drop.service
-rw-r--r--.  1 root root   757 Mar  6  2015 systemd-readahead-replay.service
-rw-r--r--.  1 root root   552 Mar  6  2015 systemd-reboot.service
-rw-r--r--.  1 root root   828 Mar  6  2015 systemd-remount-fs.service
-rw-r--r--.  1 root root   479 Mar  6  2015 systemd-shutdownd.service
-rw-r--r--.  1 root root   528 Mar  6  2015 systemd-shutdownd.socket
-rw-r--r--.  1 root root   501 Mar  6  2015 systemd-suspend.service
-rw-r--r--.  1 root root   900 Mar  6  2015 systemd-sysctl.service
-rw-r--r--.  1 root root   593 Mar  6  2015 systemd-timedated.service
-rw-r--r--.  1 root root   853 Mar  6  2015 systemd-tmpfiles-clean.service
-rw-r--r--.  1 root root   450 Mar  6  2015 systemd-tmpfiles-clean.timer
-rw-r--r--.  1 root root   622 Mar  6  2015 systemd-tmpfiles-setup-dev.service
-rw-r--r--.  1 root root  1007 Mar  6  2015 systemd-tmpfiles-setup.service
-rw-r--r--.  1 root root   578 Mar  6  2015 systemd-udevd-control.socket
-rw-r--r--.  1 root root   575 Mar  6  2015 systemd-udevd-kernel.socket
-rw-r--r--.  1 root root   772 Mar  6  2015 systemd-udevd.service
-rw-r--r--.  1 root root   827 Mar  6  2015 systemd-udev-settle.service
-rw-r--r--.  1 root root   723 Mar  6  2015 systemd-udev-trigger.service
-rw-r--r--.  1 root root   761 Mar  6  2015 systemd-update-utmp-runlevel.service
-rw-r--r--.  1 root root   831 Mar  6  2015 systemd-update-utmp.service
-rw-r--r--.  1 root root   558 Mar  6  2015 systemd-user-sessions.service
-rw-r--r--.  1 root root   690 Mar  6  2015 systemd-vconsole-setup.service
-rw-r--r--.  1 root root   433 Mar  6  2015 system.slice
-rw-r--r--.  1 root root   652 Mar  6  2015 system-update.target
-rw-r--r--.  1 root root   148 Jun 10  2014 tcsd.service
-rw-r--r--.  1 root root   193 Nov  6  2014 teamd@.service
-rw-r--r--.  1 root root   355 Mar  6  2015 timers.target
drwxr-xr-x.  2 root root    41 Mar 31  2015 timers.target.wants
-rw-r--r--.  1 root root   509 Mar  6  2015 time-sync.target
-rw-r--r--.  1 root root   669 Mar  6  2015 tmp.mount
-rw-r--r--.  1 root root   240 Oct 17  2014 tuned.service
-rw-r--r--.  1 root root   159 Jun 10  2014 udisks2.service
-rw-r--r--.  1 root root   417 Mar  6  2015 umount.target
-rw-r--r--.  1 root root   429 Jun 10  2014 upower.service
-rw-r--r--.  1 root root   123 Jun 10  2014 usbmuxd.service
-rw-r--r--.  1 root root   392 Mar  6  2015 user.slice
-rw-r--r--.  1 root root   162 Jun 10  2014 wacom-inputattach@.service
-rwxr-xr-x.  1 root root   365 Dec  4  2014 wpa_supplicant.service
```

**Comment by initstring** [comment]
Excellent feedback, thank you so much for taking the time to report this!
I am a bit busy for the next couple days but will push a fix for this as soon as possible.

**Comment by initstring** [comment]
I pushed a simple fix for this last night.
Also, just a heads up that the sudo checker was removed a few commits ago, due to the annoying pauses and the fact that it is just unnecessary. I saw your comment in your wrapper script about that so figured I'd mention it.
Good luck research!
